# Generated by Django 5.2.14 on 2026-05-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('mode', models.CharField(choices=[('diary', 'Diary'), ('opic', 'Opic')], max_length=10)),
                ('text', models.TextField()),
                ('feedback', models.JSONField(blank=True, null=True)),
                ('raw_feedback', models.TextField(blank=True, null=True)),
                ('model', models.CharField(default='haiku', max_length=40)),
                ('opic_combo', models.CharField(blank=True, max_length=50, null=True)),
                ('opic_question_index', models.IntegerField(blank=True, null=True)),
                ('opic_question_text', models.TextField(blank=True, null=True)),
                ('opic_question_type', models.CharField(blank=True, max_length=50, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
            ],
        ),
    ]
