# Generated by Django 5.2.14 on 2026-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=200, unique=True)),
                ('ko', models.CharField(max_length=300)),
                ('example', models.TextField(blank=True, default='')),
                ('tip', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
