# Generated by Django 5.2.14 on 2026-05-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='source',
            field=models.CharField(choices=[('curated', 'Curated'), ('feedback', 'From feedback')], db_index=True, default='curated', max_length=20),
        ),
        migrations.AddField(
            model_name='expression',
            name='source_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_expressions', to='api.entry'),
        ),
        migrations.AddField(
            model_name='expression',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_expressions', to='api.user'),
        ),
    ]
