# Generated by Django 5.2.14 on 2026-05-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_expression_source_expression_source_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='source',
            field=models.CharField(choices=[('curated', 'Curated'), ('feedback', 'From feedback'), ('user_note', 'From user note')], db_index=True, default='curated', max_length=20),
        ),
    ]
