# Generated by Django 5.2.14 on 2026-05-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_expression_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='audio_filename',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
