"""
저장된 알림 스케줄(notify_start_hour / notify_interval_hours / notify_count)을
컨테이너 내부 cron 파일로 변환해서 /etc/cron.d/opic-daily에 기록.

cron 데몬은 /etc/cron.d/의 파일 변경을 자동 감지하므로(보통 1분 이내) 즉시 반영됨.

호스트(파일 쓰기 권한 없음)에서는 조용히 스킵하고, 어떤 cron 라인이 만들어질지 stdout에 출력만 한다.

Usage:
    python manage.py write_crontab           # 기본 경로 (/etc/cron.d/opic-daily)
    python manage.py write_crontab --print   # 파일 안 쓰고 stdout으로만
    python manage.py write_crontab --path /tmp/foo
"""
from pathlib import Path

from django.core.management.base import BaseCommand

from api.views import get_settings, compute_notify_hours


DEFAULT_PATH = '/etc/cron.d/opic-daily'

HEADER = """SHELL=/bin/sh
PATH=/usr/local/bin:/usr/bin:/bin

# Generated by `python manage.py write_crontab` from app settings.
# 사용자가 ⚙️ 설정 UI에서 알림 스케줄을 바꾸면 자동으로 다시 작성됨.
"""


class Command(BaseCommand):
    help = "Regenerate /etc/cron.d/opic-daily from current notify schedule settings"

    def add_arguments(self, parser):
        parser.add_argument('--print', action='store_true', help='파일 쓰지 않고 출력만')
        parser.add_argument('--path', default=DEFAULT_PATH, help=f'대상 경로 (기본 {DEFAULT_PATH})')

    def handle(self, *args, **options):
        s = get_settings()
        hours = compute_notify_hours(s)
        body = HEADER
        if not hours:
            body += '# 알림 비활성화 (count=0)\n'
        else:
            for h in hours:
                body += f'{0} {h} * * * root cd /app && /usr/local/bin/python manage.py notify >> /app/data/notify.log 2>&1\n'

        if options['print']:
            self.stdout.write(body)
            return

        target = Path(options['path'])
        try:
            target.write_text(body)
            try:
                target.chmod(0o644)
            except Exception:
                pass
            self.stdout.write(self.style.SUCCESS(
                f'✅ crontab 작성 → {target} ({len(hours)}개 시점: {hours})'
            ))
        except PermissionError:
            self.stdout.write(self.style.WARNING(
                f'⚠️  {target} 쓰기 권한 없음 (호스트에서 실행 중인 듯). '
                f'Docker 컨테이너 안에서 실행하거나 --print로 라인만 확인하세요.'
            ))
        except FileNotFoundError:
            self.stdout.write(self.style.WARNING(
                f'⚠️  {target.parent} 디렉터리 없음 (cron 미설치 환경?). 스킵.'
            ))
