from django.urls import path
from . import views

urlpatterns = [
    path('health/', views.health, name='health'),
    path('opic-combo-stats/', views.opic_combo_stats, name='opic_combo_stats'),
    path('expressions/random/', views.expression_random, name='expression_random'),
    path('expressions/', views.expression_list, name='expression_list'),
    path('expressions/categories/', views.expression_categories, name='expression_categories'),
    path('quotes/', views.quotes_list, name='quotes_list'),
    path('auth/login/', views.auth_login, name='auth_login'),
    path('auth/admin/', views.auth_admin_check, name='auth_admin'),
    path('admin/users/', views.admin_users, name='admin_users'),
    path('admin/users/<str:username>/', views.admin_user_detail, name='admin_user_detail'),
    path('admin/expressions/fetch/', views.admin_expressions_fetch, name='admin_expressions_fetch'),
    path('admin/expressions/extract/', views.admin_expressions_extract, name='admin_expressions_extract'),
    path('admin/expressions/enrich/', views.admin_expressions_enrich, name='admin_expressions_enrich'),
    path('admin/expressions/from-notes/', views.admin_expressions_from_notes, name='admin_expressions_from_notes'),
    path('admin/expressions/save-notes/', views.admin_expressions_save_notes, name='admin_expressions_save_notes'),
    path('admin/quotes/fetch/', views.admin_quotes_fetch, name='admin_quotes_fetch'),
    path('admin/combos/fetch/', views.admin_combos_fetch, name='admin_combos_fetch'),
    path('admin/combos/from-notes/', views.admin_combos_from_notes, name='admin_combos_from_notes'),
    path('admin/combos/save-notes/', views.admin_combos_save_notes, name='admin_combos_save_notes'),
    path('combos/extras/', views.combos_extras_list, name='combos_extras_list'),
    path('diagnose/', views.diagnose, name='diagnose'),
    path('entries/', views.entries_collection, name='entries'),
    path('entries/<int:entry_id>/', views.entry_detail, name='entry_detail'),
    path('entries/<int:entry_id>/audio/', views.entry_audio, name='entry_audio'),
    path('feedback/', views.feedback, name='feedback'),
    path('import/', views.import_data, name='import'),
    path('settings/', views.settings_view, name='settings'),
    path('test-notify/', views.test_notify, name='test_notify'),
    path('run-notify/', views.run_notify, name='run_notify'),
    path('transcribe/', views.transcribe, name='transcribe'),
]
